version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          venv-path: '[".venv"]'
      - run:
          name: Run tests
          command: poetry run pytest --cov=monkey
      - run:
          name: Run type checking
          command: poetry run mypy
      - run:
          name: Run code formatting
          command: poetry run black --check .

workflows:
  build:
    jobs:
      - build-and-test
